# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HyRA6k-kSvsawSC6xaovAnzFcuJyDrFQ
"""

!sudo apt-get install -y zstd -q
!curl -fsSL https://ollama.ai/install.sh | sh
!pip install -q langchain langgraph langchain-ollama

import subprocess, time
subprocess.Popen(["ollama", "serve"], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
time.sleep(5)
!ollama pull llama3.2
print("✅ Setup complete")

import json, os, re
from typing import TypedDict, Optional
from langgraph.graph import StateGraph, END
from langchain_ollama import ChatOllama
from langchain_core.messages import HumanMessage, SystemMessage, AIMessage


kb = {
  "plans": {
    "basic": {"price": "$29/month", "videos": 10, "resolution": "720p", "support": "standard"},
    "pro": {"price": "$79/month", "videos": "unlimited", "resolution": "4K",
            "extras": ["AI captions", "24/7 support"]}
  },
  "policies": {
    "refund": "No refunds after 7 days",
    "support": "24/7 support on Pro plan only"
  }
}
with open("knowledge_base.json", "w") as f:
    json.dump(kb, f, indent=2)

KNOWLEDGE_BASE = """
PLANS:
- Basic: $29/month, 10 videos/month, 720p, standard support
- Pro: $79/month, unlimited videos, 4K, AI captions, 24/7 support

POLICIES:
- No refunds after 7 days
- 24/7 support only on Pro plan
"""

print("✅ Knowledge base ready")
print(KNOWLEDGE_BASE)

def mock_lead_capture(name: str, email: str, platform: str) -> str:
    if not name or not email or not platform:
        return "❌ Missing info."
    if "@" not in email or "." not in email:
        return "❌ Invalid email."
    print("\n" + "="*45)
    print("🎯 LEAD CAPTURED SUCCESSFULLY")
    print(f"   Name     : {name}")
    print(f"   Email    : {email}")
    print(f"   Platform : {platform}")
    print("="*45 + "\n")
    return f"Lead captured successfully: {name}, {email}, {platform}"

mock_lead_capture("Jane Doe", "jane@example.com", "YouTube")

llm = ChatOllama(model="llama3.2", temperature=0.1)

SYSTEM_PROMPT = f"""You are Aria, sales assistant for AutoStream (video editing SaaS).

KNOWLEDGE BASE:
{KNOWLEDGE_BASE}

YOUR WORKFLOW — follow this exact order:
STEP 1: Answer any pricing or product questions using ONLY the knowledge base above.
STEP 2: When user says they want to sign up or try a plan, ask: "Great! What's your full name?"
STEP 3: After user gives name, ask: "Thanks! What's your email address?"
STEP 4: After user gives email, ask: "Which platform do you create on? (YouTube, Instagram, TikTok, etc.)"
STEP 5: After user gives platform, write this on the last line: LEAD_READY: name | email | platform

IMPORTANT RULES:
- Never fill in name/email/platform yourself
- Only use values the user actually typed
- Ask ONE question at a time
- Keep responses short and friendly"""

class AgentState(TypedDict):
    messages: list
    intent: str
    lead_name: Optional[str]
    lead_email: Optional[str]
    lead_platform: Optional[str]
    lead_captured: bool
    turn_count: int

print("✅ LLM + State ready")

def detect_intent(msg: str) -> str:
    msg = msg.lower()
    high_intent = ["sign up", "sign me up", "i want to try", "interested",
                   "let's go", "get started", "subscribe", "buy", "purchase",
                   "i want the pro", "i want the basic", "register", "want to try"]
    greetings = ["hi", "hello", "hey", "good morning", "howdy"]
    for phrase in high_intent:
        if phrase in msg:
            return "high_intent"
    if any(msg.strip().startswith(g) for g in greetings) and len(msg.split()) < 6:
        return "greeting"
    return "inquiry"

def extract_lead_signal(text: str):
    match = re.search(r"LEAD_READY:\s*(.+?)\s*\|\s*(.+?)\s*\|\s*(.+)", text, re.IGNORECASE)
    if match:
        return match.group(1).strip(), match.group(2).strip(), match.group(3).strip()
    return None

def chat_node(state: AgentState) -> AgentState:
    messages = state["messages"]
    turn_count = state.get("turn_count", 0) + 1
    lead_captured = state.get("lead_captured", False)

    latest = next((m["content"] for m in reversed(messages) if m["role"] == "user"), "")
    intent = detect_intent(latest)

    # Handle pricing questions directly from knowledge base — no LLM needed
    pricing_keywords = ["pricing", "plans", "cost", "how much", "tell me about your pricing", "what do you offer"]
    is_pricing_question = any(k in latest.lower() for k in pricing_keywords)
    is_high_intent = detect_intent(latest) == "high_intent"

    if is_pricing_question and not is_high_intent and not lead_captured:
        clean = """Here's what we offer at AutoStream:

📦 Basic Plan — $29/month
- 10 videos/month
- 720p resolution
- Standard support

🚀 Pro Plan — $79/month
- Unlimited videos
- 4K resolution
- AI captions included
- 24/7 priority support

No refunds after 7 days. Interested in signing up?"""
        return {**state,
                "messages": messages + [{"role": "assistant", "content": clean}],
                "intent": "inquiry", "lead_captured": lead_captured, "turn_count": turn_count}

    # All other messages go through LLM
    llm_messages = [SystemMessage(content=SYSTEM_PROMPT)]
    for msg in messages:
        if msg["role"] == "user":
            llm_messages.append(HumanMessage(content=msg["content"]))
        elif msg["role"] == "assistant":
            llm_messages.append(AIMessage(content=msg["content"]))

    response = llm.invoke(llm_messages)
    response_text = response.content
    lead_info = extract_lead_signal(response_text)
    clean = re.sub(r"LEAD_READY:.*", "", response_text, flags=re.IGNORECASE).strip()

    if lead_info and not lead_captured:
        name, email, platform = lead_info
        mock_lead_capture(name, email, platform)
        clean += f"\n\n✅ You're all set, {name}! Our team will reach out shortly."
        return {**state,
                "messages": messages + [{"role": "assistant", "content": clean}],
                "intent": "high_intent", "lead_name": name, "lead_email": email,
                "lead_platform": platform, "lead_captured": True, "turn_count": turn_count}

    return {**state,
            "messages": messages + [{"role": "assistant", "content": clean}],
            "intent": intent, "lead_captured": lead_captured, "turn_count": turn_count}

print("✅ Agent logic updated")

def should_end(state: AgentState) -> str:
    if state.get("lead_captured"): return END
    if state.get("turn_count", 0) >= 10: return END
    return "chat"

print("✅ Agent logic ready")

workflow = StateGraph(AgentState)
workflow.add_node("chat", chat_node)
workflow.set_entry_point("chat")
workflow.add_conditional_edges("chat", should_end, {"chat": "chat", END: END})
app = workflow.compile()
print("✅ Graph compiled")

import httpx, subprocess, time
try:
    httpx.get("http://localhost:11434")
except:
    subprocess.Popen(["ollama", "serve"], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    time.sleep(8)
conversation_state = {
    "messages": [], "intent": "greeting",
    "lead_name": None, "lead_email": None, "lead_platform": None,
    "lead_captured": False, "turn_count": 0,
}

demo_inputs = [
    "Hi, tell me about your pricing.",
    "What is included in the Pro plan?",              # ← forces RAG response
    "That sounds good, I want to try the Pro plan for my YouTube channel.",
    "Rahul Sharma",
    "rahul@gmail.com",
    "YouTube"
]

print("="*50)
print("  AutoStream AI Agent — Conversation Demo")
print("="*50 + "\n")

for user_input in demo_inputs:
    print(f"User : {user_input}")
    conversation_state["messages"].append({"role": "user", "content": user_input})
    conversation_state = app.invoke(conversation_state)
    last_reply = next(
        (m["content"] for m in reversed(conversation_state["messages"])
         if m["role"] == "assistant"), ""
    )
    print(f"Aria : {last_reply}\n")
    print("-"*50 + "\n")
    if conversation_state.get("lead_captured"):
        print("✅ Demo complete — lead successfully captured.")
        break